name: Deploy to S3 Website
on:
  push:
    branches:
      - Static_website_deployment  # Change if using another branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Update if needed

      - name: Sync Files to S3
        run: |
          aws s3 sync ./ s3://serverlesswebappsaikiran/ --delete --acl public-read

      - name: Post-Deployment Success
        run: echo "🎉 Website deployed to S3 successfully! Access it via the S3 Website URL."
